language: node_js
node_js:
  - 'node'

script:
  # Run regular typecheck + lint
  - npm test
  # Validate against AMO's validation
  - npm run build:firefox && npx web-ext lint -s dist
  - npm run build:firefox-beta && npx web-wext sign --api-key="$AMO_API_KEY" --api-secret="$AMO_API_SECRET" -s dist --channel unlisted;